---
title: "Phyloseq PreProcessing"
author: "Andrea Martinez"
date: "`r Sys.Date()`"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE,
                      fig.align = "center", 
                      fig.path = "../figures/02_PreProcessing/") # send any figure output to this folder
```

# Load Libraries
```{r load-libraries}
library(devtools)
install_github("joey711/phyloseq")
library(phyloseq)
```


# Goals

Here, we will process the data into a phyloseq object.

- ASV table
- Taxonomy Table
- Track Reads (metadata)

Then, we will remove the following:

1. Chloroplasts
2. Mitochondria
3. Samples without "enough" reads.

Finally, write a data file of phyloseq output

# Load Data

## ASV Table
```{r load-asv-table}
# First, load asv table
load("data/01_DADA2/ASV_counts.RData")

# Inspect asv_tab
head(asv_tab)[,1:5]

# Fix names
sample_names <- colnames(asv_tab)
samples_fixed <- sapply(strsplit(basename(sample_names), "_"), `[`,1)
head(samples_fixed)

#re-write the ASV count file to fix names
colnames(asv_tab) <- samples_fixed
str(asv_tab)
```

## Taxonomy Table
```{r load-tax-table}
tax_df <- read.table("data/01_DADA2/ASV_taxonomy.tsv", sep = "\t", skip = 1)
head(tax_df)

# fix column names
colnames(tax_df) <- c("ASV_names", "Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species", "ASV", "ASVseq")
head(tax_df)

# Taxonomy Table Matrix
tax_mat <- tax_df %>%
  tibble::column_to_rownames(., var = "ASV_names") %>%
  as.matrix()
```

## Track Reads Data
```{r load-track-reads}

```

# Handoff to phyloseq
```{r phyloseq-handoff}

```
